version: 2
jobs:
  build:
    working_directory: ~/dos-calc
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: dos-calc-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: dos-calc-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm run lint
      - run:
          command: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
          environment:
            JUNIT_REPORT_PATH: ./junit/
            JUNIT_REPORT_NAME: test-results.xml
      - store_test_results:
          path: ./junit
      - store_artifacts:
          path: ./junit
      - run: npm run build -- --prod --aot

  deploy:
    working_directory: ~/dos-calc
    docker:
      - image: buildpack-deps:trusty
    steps:
      - run:
          name: Deploy
          command: curl -X POST -d {} ${NETLIFY_HOOK}

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
