version: 2
jobs:
  build:
    working_directory: ~/rdos-calc
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: rdos-calc-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: rdos-calc-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm run lint
      - run:
          command: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
          environment:
            JUNIT_REPORT_PATH: ./junit/
            JUNIT_REPORT_NAME: test-results.xml
      - store_test_results:
          path: ./junit
      - store_artifacts:
          path: ./junit
      - run: npm run build -- --prod --aot
      - persist_to_workspace:
          root: .
          paths:
            - www

  deploy:
    working_directory: ~/rdos-calc
    machine:
      enabled: true
    steps:
      - attach_workspace:
          at: www
      - run:
          name: Deploy Over SCP
          command: |
            scp -r www/www/* "$SSH_USER@$SSH_HOST:$SSH_DEPLOY_PATH"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
